version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nowcasting_api
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - 80:80
