name: Lint Python
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2
    - name: Install Python 
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install pydocstyle flake8 isort
    - name: Docstyle linting
      run: |
          pydocstyle --convention=google --add-ignore=D200,D210,D212,D415
    - name: flake8 linting
      run: |
          flake8 --max-line-length 99
    - name: Run isort
      run: |
          isort --check --diff .
