name: Lint Python
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydocstyle flake8 isort black
      - name: Docstyle linting
        run: |
          pydocstyle --convention=google --add-ignore=D200,D202,D210,D212,D415 .
      - name: flake8 linting
        run: |
          flake8 --max-line-length 100 --extend-ignore=E203 .
      - name: Run isort
        run: |
          isort --check --diff --profile black --line-length 100 .
      - name: Run black
        run: |
          black --line-length 100 .
